## config
data_source = 'local'
threshold = 0.5
## Input Raw data

## Output Processed data
training_data_file = '/Users/apal/Documents/PathtoAI/AnalyticsVidhya/Mlops/data/Human_Activity_Recognition_Using_Smartphones_Data_augmented_data.gzip'

##Output Prediction :->
model_prediction = '../data/prediction/prediction.csv'
daily_prediction_dir = '../data/prediction/daily_prediction/'

## Pipeline feature
feature_pipeline = 'weights/pipeline/pipeline.pkl'
model_weights = 'weights/model/model.pkl'
## Columns
feat_col = "weights/pipeline/cols.pkl"
